name: Docker Image CI

on:
  push:
    branches: ["main"]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build ZuydWorld Docker image
        run: docker build . --file ZuydWorld/Dockerfile --tag zuydworld-image:latest
      - name: Push ZuydWorld Docker image
        run: |
          docker tag zuydworld-image:latest ${{ env.DOCKER_USERNAME }}/zuydworld-image:latest
          docker push ${{ env.DOCKER_USERNAME }}/zuydworld-image:latest
      - name: Build Database Docker image
        run: docker build . --file Database/Dockerfile --tag database-image:latest
      - name: Push Database Docker image
        run: |
          docker tag database-image:latest ${{ env.DOCKER_USERNAME }}/database-image:latest
          docker push ${{ env.DOCKER_USERNAME }}/database-image:latest
